"""initial schema foundation (no application tables yet)

Deliberately empty: as of this revision, no DataWise functionality
requires a relational table. Datasets/documents persist via the existing
file-backed stores (app/semantic/store.py, app/documents/store.py) and
conversation memory is intentionally session-scoped/in-memory only (see
app/agent/memory.py). This revision exists to establish the migration
chain baseline against the DataWise Neon database; the first real model
will attach its own migration on top of this one. See app/db/base.py for
the documented list of deferred future entities.

Revision ID: 1111b4a32041
Revises:
Create Date: 2026-08-23 23:57:33.094861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1111b4a32041'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
