"""add integrations and connected items

Revision ID: 840fa885136f
Revises: 7c392f48ae78
Create Date: 2026-08-30 21:27:51.951391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '840fa885136f'
down_revision: Union[str, Sequence[str], None] = '7c392f48ae78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integrations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('scopes_granted', sa.String(), nullable=False),
    sa.Column('encrypted_refresh_token', sa.String(), nullable=False),
    sa.Column('connected_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integrations_user_id'), 'integrations', ['user_id'], unique=False)
    op.create_table('connected_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('integration_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('external_kind', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('external_modified_at', sa.DateTime(), nullable=False),
    sa.Column('dataset_id', sa.String(), nullable=True),
    sa.Column('document_id', sa.String(), nullable=True),
    sa.Column('sync_status', sa.String(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['integration_id'], ['integrations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connected_items_integration_id'), 'connected_items', ['integration_id'], unique=False)
    op.create_index('ix_connected_items_user_external', 'connected_items', ['user_id', 'external_id'], unique=False)
    op.create_index(op.f('ix_connected_items_user_id'), 'connected_items', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_connected_items_user_id'), table_name='connected_items')
    op.drop_index('ix_connected_items_user_external', table_name='connected_items')
    op.drop_index(op.f('ix_connected_items_integration_id'), table_name='connected_items')
    op.drop_table('connected_items')
    op.drop_index(op.f('ix_integrations_user_id'), table_name='integrations')
    op.drop_table('integrations')
    # ### end Alembic commands ###
