"""add report email delivery status

Revision ID: af7ae394716c
Revises: 7352a4ee6249
Create Date: 2026-08-24 12:10:55.664064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af7ae394716c'
down_revision: Union[str, Sequence[str], None] = '7352a4ee6249'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    server_default is required (not autogenerated) -- the reports table
    already has real rows from this session's testing; every one becomes
    email_status='not_sent', which is correct since none of them have
    actually been emailed. Dropped again after backfilling so new rows go
    through the ORM's own default.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('email_status', sa.String(), nullable=False, server_default='not_sent'))
    op.add_column('reports', sa.Column('email_recipient', sa.String(), nullable=True))
    op.add_column('reports', sa.Column('email_sent_at', sa.DateTime(), nullable=True))
    op.alter_column('reports', 'email_status', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'email_sent_at')
    op.drop_column('reports', 'email_recipient')
    op.drop_column('reports', 'email_status')
    # ### end Alembic commands ###
