"""add user currency and decimal place preferences

Revision ID: ff52363fd06d
Revises: af7ae394716c
Create Date: 2026-08-24 13:34:44.389275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff52363fd06d'
down_revision: Union[str, Sequence[str], None] = 'af7ae394716c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default needed here: the users table already has real rows
    # (existing signups), and a NOT NULL column added without one fails
    # against them. Dropped after backfill so new rows go through the
    # ORM's own Python-level default instead of a stale DB-level one.
    op.add_column('users', sa.Column('currency', sa.String(), nullable=False, server_default='USD'))
    op.add_column('users', sa.Column('decimal_places', sa.Integer(), nullable=False, server_default='2'))
    op.alter_column('users', 'currency', server_default=None)
    op.alter_column('users', 'decimal_places', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'decimal_places')
    op.drop_column('users', 'currency')
    # ### end Alembic commands ###
